### ISSUE TITLE
Wrong sbt-scalafix version when when creating a new project with sbt new

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix.g8#10]
Following documentation in [scalafix developer guide](https://scalacenter.github.io/scalafix/docs/developers/setup.html), I end up with a non-existing version of sbt-scalafix :
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "2.3.0-RC1")
```

**Comment by olafurpg** [comment]
Thank you for reporting! There seems to be a 2.3.0-RC1 release of scalafix-core_2.12 🤔 

```sh
❯ cs complete ch.epfl.scala:scalafix-core_2.12: | tail
0.9.7
0.9.8
0.9.9
0.9.10
0.9.11
0.9.12
0.9.13
0.9.14
0.9.15
2.3.0-RC1
```

We can try to fix this by changing the artifact name below to use scalafix-cli_2.12.11 instead

https://github.com/scalacenter/scalafix.g8/blob/c22ae75cabb629aa4a83a95d5fdd8f99691cd92b/src/main/g8/default.properties#L3
